apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backend-metrics-reader
  namespace: cloud-scaling-demo
rules:
  - apiGroups:
      - metrics.k8s.io
    resources:
      - pods
    verbs:
      - get
      - list
