apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloud-scaling-demo
resources:
  - namespace.yaml
  - backend-configmap.yaml
  - backend-serviceaccount.yaml
  - backend-metrics-reader-role.yaml
  - backend-metrics-reader-rolebinding.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - backend-hpa.yaml
  - backend-pdb.yaml
  - frontend-configmap.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
